### ISSUE TITLE
TOR Crawler Error and TimeoutError

### ISSUE THREAD

**Issue by Pranav-2301** [ail-project/lacus#23]
<img width="1501" alt="Screenshot 2024-09-17 at 3 50 41 AM" src="https://github.com/user-attachments/assets/7c028207-de99-4882-bac0-4b1a10492a4d">

Hello, my crawler and AIL both were working fine until I saw these flooding the CLI. 

<img width="1394" alt="Screenshot 2024-09-17 at 3 53 03 AM" src="https://github.com/user-attachments/assets/31127f6f-aba3-4688-a87e-d995aab371b7">

Can you please help me out with it ?

**Comment by Rafiot** [comment]
That log line is simply due to a non-clear shutdown of the crawler and the capturing script waits for ~1h for captures that are potentially still running in another process. It will be cleared up at some point.

Then, a timeout is going to happen on onion websites because they simply don't work, sometimes.
